/* Generated by re2c 0.11.3 on Thu Oct 25 16:41:06 2007 */
#line 1 "C:/Users/frane/Source/tmtorange/src/tmt/strings/UTF8Tokenizer.rr.cpp"
#include <string>
#include <cstdio>
#include <cstring>
#include <ctime>
#include <stdexcept>
#include <iterator>

#include "tmt/strings/UTF8Tokenizer.h"
#include "tmt/strings/StringUtils.h"

using namespace std;
using namespace TMT;

enum
{
	TokenEOT =			0x0001,
	TokenUnicodeBOM =	0x0002,
	TokenWord =			0x0004,
	TokenWhitespace =	0x0008,
	TokenURI =			0x0010,
	TokenPunctuation =	0x0020,
	TokenUnknownChar =	0x0040,
	TokenIllegalUTF8 =	0x0080
};

string UTF8Tokenizer::Token::getString() const
{
	return string(start, end - start);
}

bool UTF8Tokenizer::Token::hasDigits() const
{
	const char *c;
//	for (c = start; c < end; c = UTF8NextChar(c))
	for (c = start; c < end; ++c)
		if (*c >= '0' && *c <= '9')
			return true;
	return false;
}

bool UTF8Tokenizer::Token::isUnicodeBOM() const
{
	return !!(mask & TokenUnicodeBOM);
}

bool UTF8Tokenizer::Token::isEOT() const
{
	return !!(mask & TokenEOT);
}

bool UTF8Tokenizer::Token::isIllegalUTF8() const
{
	return !!(mask & TokenIllegalUTF8);
}

bool UTF8Tokenizer::Token::isNumber() const
{
	unsigned const char *q;
	unsigned const char *p = reinterpret_cast<unsigned const char *>(start);
#define YYCTYPE         int
#define YYCURSOR        p
#define YYLIMIT         p
#define YYMARKER        q
#define YYFILL(n) 

#line 69 "C:/Users/frane/Source/tmtorange/src/../export/tmt/strings/UTF8Tokenizer.cpp"
{
	YYCTYPE yych;

	if((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if(yych <= 0x00) goto yy6;
	if(yych <= '/') goto yy4;
	if(yych >= ':') goto yy4;
	yych = *(YYMARKER = ++YYCURSOR);
	goto yy9;
yy3:
#line 72 "C:/Users/frane/Source/tmtorange/src/tmt/strings/UTF8Tokenizer.rr.cpp"
	{ return p == reinterpret_cast<unsigned const char *>(end); }
#line 83 "C:/Users/frane/Source/tmtorange/src/../export/tmt/strings/UTF8Tokenizer.cpp"
yy4:
	++YYCURSOR;
#line 73 "C:/Users/frane/Source/tmtorange/src/tmt/strings/UTF8Tokenizer.rr.cpp"
	{ return false; }
#line 88 "C:/Users/frane/Source/tmtorange/src/../export/tmt/strings/UTF8Tokenizer.cpp"
yy6:
	++YYCURSOR;
#line 74 "C:/Users/frane/Source/tmtorange/src/tmt/strings/UTF8Tokenizer.rr.cpp"
	{ return false; }
#line 93 "C:/Users/frane/Source/tmtorange/src/../export/tmt/strings/UTF8Tokenizer.cpp"
yy8:
	YYMARKER = ++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy9:
	if(yych <= '/') {
		if(yych <= ',') {
			if(yych <= '+') goto yy3;
		} else {
			if(yych != '.') goto yy3;
		}
	} else {
		if(yych <= ';') {
			if(yych <= '9') goto yy8;
			if(yych <= ':') goto yy3;
		} else {
			if(yych == 0xE2) goto yy12;
			goto yy3;
		}
	}
yy10:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= '/') goto yy11;
	if(yych <= '9') goto yy8;
yy11:
	YYCURSOR = YYMARKER;
	goto yy3;
yy12:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych != 0x81) goto yy11;
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == 0x84) goto yy10;
	goto yy11;
}
#line 75 "C:/Users/frane/Source/tmtorange/src/tmt/strings/UTF8Tokenizer.rr.cpp"

#undef YYCTYPE
#undef YYCURSOR
#undef YYLIMIT
#undef YYMARKER
#undef YYFILL
	return false;
}

bool UTF8Tokenizer::Token::isPunctuation() const
{
	return !!(mask & TokenPunctuation);
}

bool UTF8Tokenizer::Token::isURI() const
{
	return !!(mask & TokenURI);
}

bool UTF8Tokenizer::Token::isWhitespace() const
{
	return !!(mask & TokenWhitespace);
}

bool UTF8Tokenizer::Token::isWord() const
{
	return !!(mask & TokenWord);
}

unsigned const char *UTF8Tokenizer::TokenIterator::scan (unsigned const char *p)
{
	unsigned const char *q;
#define YYCTYPE         int
#define YYCURSOR        p
#define YYLIMIT         p
#define YYMARKER        q
#define YYFILL(n) 

#line 173 "C:/Users/frane/Source/tmtorange/src/../export/tmt/strings/UTF8Tokenizer.cpp"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	if((YYLIMIT - YYCURSOR) < 9) YYFILL(9);
	yych = *YYCURSOR;
	if(yych <= 'z') {
		if(yych <= '+') {
			if(yych <= 0x0D) {
				if(yych <= 0x08) {
					if(yych <= 0x00) goto yy45;
					goto yy40;
				} else {
					if(yych <= 0x0A) goto yy34;
					if(yych <= 0x0C) goto yy40;
					goto yy34;
				}
			} else {
				if(yych <= '#') {
					if(yych <= 0x1F) goto yy40;
					if(yych <= ' ') goto yy34;
					goto yy38;
				} else {
					if(yych <= '$') goto yy40;
					if(yych <= '*') goto yy38;
					goto yy40;
				}
			}
		} else {
			if(yych <= '@') {
				if(yych <= ';') {
					if(yych <= '/') goto yy38;
					if(yych <= '9') goto yy33;
					goto yy38;
				} else {
					if(yych <= '<') goto yy36;
					if(yych <= '>') goto yy40;
					goto yy38;
				}
			} else {
				if(yych <= '^') {
					if(yych <= 'Z') goto yy18;
					if(yych <= ']') goto yy38;
					goto yy40;
				} else {
					if(yych <= '_') goto yy38;
					if(yych <= '`') goto yy40;
					goto yy20;
				}
			}
		}
	} else {
		if(yych <= 0xC8) {
			if(yych <= 0xC1) {
				if(yych <= '}') {
					if(yych == '|') goto yy40;
					goto yy38;
				} else {
					if(yych <= 0x7F) goto yy40;
					if(yych <= 0xBF) goto yy44;
					goto yy41;
				}
			} else {
				if(yych <= 0xC5) {
					if(yych <= 0xC2) goto yy21;
					if(yych <= 0xC3) goto yy22;
					goto yy24;
				} else {
					if(yych <= 0xC6) goto yy23;
					if(yych <= 0xC7) goto yy25;
					goto yy27;
				}
			}
		} else {
			if(yych <= 0xE1) {
				if(yych <= 0xCB) {
					if(yych <= 0xC9) goto yy26;
					if(yych <= 0xCA) goto yy28;
					goto yy29;
				} else {
					if(yych <= 0xDF) goto yy41;
					if(yych <= 0xE0) goto yy42;
					goto yy30;
				}
			} else {
				if(yych <= 0xEE) {
					if(yych <= 0xE2) goto yy31;
					if(yych <= 0xE3) goto yy32;
					goto yy42;
				} else {
					if(yych <= 0xEF) goto yy16;
					if(yych <= 0xF7) goto yy43;
					goto yy44;
				}
			}
		}
	}
yy16:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= 0xBA) {
		if(yych <= 0x7F) goto yy17;
		if(yych == 0xAC) goto yy327;
		goto yy51;
	} else {
		if(yych <= 0xBC) {
			if(yych <= 0xBB) goto yy328;
			goto yy329;
		} else {
			if(yych <= 0xBD) goto yy330;
			if(yych <= 0xBF) goto yy51;
		}
	}
yy17:
#line 183 "C:/Users/frane/Source/tmtorange/src/tmt/strings/UTF8Tokenizer.rr.cpp"
	{ token.mask = TokenIllegalUTF8;	return YYCURSOR; }
#line 289 "C:/Users/frane/Source/tmtorange/src/../export/tmt/strings/UTF8Tokenizer.cpp"
yy18:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= '.') {
		if(yych <= '+') {
			if(yych == '\'') goto yy145;
			goto yy149;
		} else {
			if(yych == '-') goto yy149;
		}
	} else {
		if(yych <= 0xC1) {
			if(yych != ';') goto yy149;
		} else {
			if(yych <= 0xC2) goto yy146;
			if(yych == 0xE2) goto yy147;
			goto yy149;
		}
	}
yy19:
#line 178 "C:/Users/frane/Source/tmtorange/src/tmt/strings/UTF8Tokenizer.rr.cpp"
	{ token.mask = TokenWord;			return YYCURSOR; }
#line 312 "C:/Users/frane/Source/tmtorange/src/../export/tmt/strings/UTF8Tokenizer.cpp"
yy20:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= ':') {
		if(yych <= ',') {
			if(yych == '\'') goto yy145;
			if(yych <= '+') goto yy149;
			goto yy19;
		} else {
			if(yych == '.') goto yy19;
			if(yych <= '9') goto yy149;
			goto yy319;
		}
	} else {
		if(yych <= 0xC1) {
			if(yych <= ';') goto yy19;
			if(yych <= '`') goto yy149;
			if(yych <= 'z') goto yy320;
			goto yy149;
		} else {
			if(yych <= 0xC2) goto yy146;
			if(yych == 0xE2) goto yy147;
			goto yy149;
		}
	}
yy21:
	yych = *++YYCURSOR;
	if(yych <= 0xB4) {
		if(yych <= 0xA1) {
			if(yych <= 0x7F) goto yy17;
			if(yych <= 0x9F) goto yy50;
			if(yych <= 0xA0) goto yy318;
			goto yy310;
		} else {
			if(yych <= 0xA9) goto yy50;
			if(yych <= 0xAA) goto yy144;
			if(yych <= 0xAB) goto yy310;
			goto yy50;
		}
	} else {
		if(yych <= 0xB9) {
			if(yych <= 0xB5) goto yy144;
			if(yych == 0xB7) goto yy310;
			goto yy50;
		} else {
			if(yych <= 0xBB) {
				if(yych <= 0xBA) goto yy144;
				goto yy310;
			} else {
				if(yych <= 0xBE) goto yy50;
				if(yych <= 0xBF) goto yy310;
				goto yy17;
			}
		}
	}
yy22:
	yych = *++YYCURSOR;
	if(yych <= 0x97) {
		if(yych <= 0x7F) goto yy17;
		if(yych <= 0x96) goto yy144;
		goto yy50;
	} else {
		if(yych == 0xB7) goto yy50;
		if(yych <= 0xBF) goto yy144;
		goto yy17;
	}
yy23:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy17;
	if(yych <= 0xBF) goto yy144;
	goto yy17;
yy24:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy17;
	if(yych <= 0xBF) goto yy144;
	goto yy17;
yy25:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy17;
	if(yych <= 0xBF) goto yy144;
	goto yy17;
yy26:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy17;
	if(yych <= 0x81) goto yy144;
	if(yych <= 0x8F) goto yy50;
	if(yych <= 0xBF) goto yy144;
	goto yy17;
yy27:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy17;
	if(yych <= 0xBF) goto yy144;
	goto yy17;
yy28:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy17;
	if(yych <= 0xBF) goto yy144;
	goto yy17;
yy29:
	yych = *++YYCURSOR;
	if(yych <= 0x9F) {
		if(yych <= 0x81) {
			if(yych <= 0x7F) goto yy17;
			goto yy144;
		} else {
			if(yych <= 0x85) goto yy50;
			if(yych <= 0x91) goto yy144;
			goto yy50;
		}
	} else {
		if(yych <= 0xAD) {
			if(yych <= 0xA4) goto yy144;
			goto yy50;
		} else {
			if(yych <= 0xAE) goto yy144;
			if(yych <= 0xBF) goto yy50;
			goto yy17;
		}
	}
yy30:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= 0xB7) {
		if(yych <= 0xB4) {
			if(yych <= 0x7F) goto yy17;
			if(yych <= 0xB3) goto yy51;
			goto yy311;
		} else {
			if(yych <= 0xB5) goto yy312;
			if(yych <= 0xB6) goto yy313;
			goto yy51;
		}
	} else {
		if(yych <= 0xBA) {
			if(yych <= 0xB8) goto yy314;
			if(yych <= 0xB9) goto yy315;
			goto yy316;
		} else {
			if(yych <= 0xBB) goto yy317;
			if(yych <= 0xBF) goto yy51;
			goto yy17;
		}
	}
yy31:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= 0x91) {
		if(yych <= 0x7F) goto yy17;
		if(yych <= 0x80) goto yy306;
		if(yych <= 0x81) goto yy307;
		goto yy51;
	} else {
		if(yych <= 0x92) goto yy308;
		if(yych <= 0x93) goto yy309;
		if(yych <= 0xBF) goto yy51;
		goto yy17;
	}
yy32:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= 0x7F) goto yy17;
	if(yych <= 0x80) goto yy143;
	if(yych <= 0xBF) goto yy51;
	goto yy17;
yy33:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	goto yy67;
yy34:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	goto yy62;
yy35:
#line 179 "C:/Users/frane/Source/tmtorange/src/tmt/strings/UTF8Tokenizer.rr.cpp"
	{ token.mask = TokenWhitespace;		return YYCURSOR; }
#line 488 "C:/Users/frane/Source/tmtorange/src/../export/tmt/strings/UTF8Tokenizer.cpp"
yy36:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= '`') goto yy37;
	if(yych <= 'z') goto yy52;
yy37:
#line 182 "C:/Users/frane/Source/tmtorange/src/tmt/strings/UTF8Tokenizer.rr.cpp"
	{ token.mask = TokenUnknownChar;	return YYCURSOR; }
#line 497 "C:/Users/frane/Source/tmtorange/src/../export/tmt/strings/UTF8Tokenizer.cpp"
yy38:
	++YYCURSOR;
yy39:
#line 181 "C:/Users/frane/Source/tmtorange/src/tmt/strings/UTF8Tokenizer.rr.cpp"
	{ token.mask = TokenPunctuation;	return YYCURSOR; }
#line 503 "C:/Users/frane/Source/tmtorange/src/../export/tmt/strings/UTF8Tokenizer.cpp"
yy40:
	yych = *++YYCURSOR;
	goto yy37;
yy41:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy17;
	if(yych <= 0xBF) goto yy50;
	goto yy17;
yy42:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= 0x7F) goto yy17;
	if(yych <= 0xBF) goto yy51;
	goto yy17;
yy43:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= 0x7F) goto yy17;
	if(yych <= 0xBF) goto yy47;
	goto yy17;
yy44:
	yych = *++YYCURSOR;
	goto yy17;
yy45:
	++YYCURSOR;
#line 184 "C:/Users/frane/Source/tmtorange/src/tmt/strings/UTF8Tokenizer.rr.cpp"
	{ token.mask = TokenEOT;			return YYCURSOR; }
#line 531 "C:/Users/frane/Source/tmtorange/src/../export/tmt/strings/UTF8Tokenizer.cpp"
yy47:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy49;
yy48:
	YYCURSOR = YYMARKER;
	if(yyaccept <= 2) {
		if(yyaccept <= 1) {
			if(yyaccept <= 0) {
				goto yy17;
			} else {
				goto yy19;
			}
		} else {
			goto yy35;
		}
	} else {
		if(yyaccept <= 3) {
			goto yy37;
		} else {
			goto yy60;
		}
	}
yy49:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych >= 0xC0) goto yy48;
yy50:
	yych = *++YYCURSOR;
	goto yy37;
yy51:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy50;
	goto yy48;
yy52:
	++YYCURSOR;
	if((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	if(yych == ':') goto yy54;
	if(yych <= '`') goto yy48;
	if(yych <= 'z') goto yy52;
	goto yy48;
yy54:
	yych = *++YYCURSOR;
	if(yych != '/') goto yy48;
	yych = *++YYCURSOR;
	if(yych != '/') goto yy48;
yy56:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= '@') {
		if(yych <= '+') {
			if(yych <= '#') {
				if(yych <= ' ') goto yy48;
				goto yy56;
			} else {
				if(yych <= '$') goto yy58;
				if(yych <= '*') goto yy56;
			}
		} else {
			if(yych <= ';') {
				if(yych <= '.') goto yy56;
				if(yych >= ':') goto yy56;
			} else {
				if(yych <= '<') goto yy48;
				if(yych >= '?') goto yy56;
			}
		}
	} else {
		if(yych <= '_') {
			if(yych <= '\\') {
				if(yych == '[') goto yy56;
			} else {
				if(yych != '^') goto yy56;
			}
		} else {
			if(yych <= '|') {
				if(yych == '{') goto yy56;
			} else {
				if(yych <= '}') goto yy56;
				if(yych >= 0x7F) goto yy48;
			}
		}
	}
yy58:
	yyaccept = 4;
	YYMARKER = ++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= '@') {
		if(yych <= '+') {
			if(yych <= '#') {
				if(yych >= '!') goto yy56;
			} else {
				if(yych <= '$') goto yy58;
				if(yych <= '*') goto yy56;
				goto yy58;
			}
		} else {
			if(yych <= ';') {
				if(yych <= '.') goto yy56;
				if(yych <= '9') goto yy58;
				goto yy56;
			} else {
				if(yych <= '<') goto yy60;
				if(yych <= '>') goto yy58;
				goto yy56;
			}
		}
	} else {
		if(yych <= '_') {
			if(yych <= '\\') {
				if(yych == '[') goto yy56;
				goto yy58;
			} else {
				if(yych == '^') goto yy58;
				goto yy56;
			}
		} else {
			if(yych <= '|') {
				if(yych == '{') goto yy56;
				goto yy58;
			} else {
				if(yych <= '}') goto yy56;
				if(yych <= '~') goto yy58;
			}
		}
	}
yy60:
#line 180 "C:/Users/frane/Source/tmtorange/src/tmt/strings/UTF8Tokenizer.rr.cpp"
	{ token.mask = TokenURI;			return YYCURSOR; }
#line 665 "C:/Users/frane/Source/tmtorange/src/../export/tmt/strings/UTF8Tokenizer.cpp"
yy61:
	yyaccept = 2;
	YYMARKER = ++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy62:
	if(yych <= 0x0D) {
		if(yych <= 0x08) goto yy35;
		if(yych <= 0x0A) goto yy61;
		if(yych <= 0x0C) goto yy35;
		goto yy61;
	} else {
		if(yych <= ' ') {
			if(yych <= 0x1F) goto yy35;
			goto yy61;
		} else {
			if(yych != 0xC2) goto yy35;
		}
	}
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == 0xA0) goto yy61;
	goto yy48;
yy64:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= '/') goto yy48;
	if(yych <= '9') goto yy135;
	goto yy48;
yy65:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x91) {
		if(yych == 0x81) goto yy134;
		goto yy48;
	} else {
		if(yych <= 0x92) goto yy101;
		if(yych <= 0x93) goto yy100;
		goto yy48;
	}
yy66:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy67:
	if(yych <= 0xC2) {
		if(yych <= ':') {
			if(yych <= '-') {
				if(yych == ',') goto yy64;
				goto yy19;
			} else {
				if(yych <= '.') goto yy64;
				if(yych <= '/') goto yy19;
				if(yych <= '9') goto yy66;
				goto yy19;
			}
		} else {
			if(yych <= 'Z') {
				if(yych <= ';') goto yy64;
				if(yych <= '@') goto yy19;
			} else {
				if(yych <= '`') goto yy19;
				if(yych <= 'z') goto yy68;
				if(yych <= 0xC1) goto yy19;
				goto yy70;
			}
		}
	} else {
		if(yych <= 0xCA) {
			if(yych <= 0xC6) {
				if(yych <= 0xC3) goto yy71;
				if(yych <= 0xC5) goto yy73;
				goto yy72;
			} else {
				if(yych <= 0xC7) goto yy74;
				if(yych <= 0xC8) goto yy76;
				if(yych <= 0xC9) goto yy75;
				goto yy77;
			}
		} else {
			if(yych <= 0xE2) {
				if(yych <= 0xCB) goto yy78;
				if(yych <= 0xE0) goto yy19;
				if(yych <= 0xE1) goto yy79;
				goto yy65;
			} else {
				if(yych <= 0xE3) goto yy80;
				if(yych == 0xEF) goto yy81;
				goto yy19;
			}
		}
	}
yy68:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xC5) {
		if(yych <= 'Z') {
			if(yych <= '/') {
				if(yych == '\'') goto yy93;
				goto yy19;
			} else {
				if(yych <= '9') goto yy96;
				if(yych <= '@') goto yy19;
				goto yy68;
			}
		} else {
			if(yych <= 0xC1) {
				if(yych <= '`') goto yy19;
				if(yych <= 'z') goto yy68;
				goto yy19;
			} else {
				if(yych <= 0xC2) goto yy94;
				if(yych <= 0xC3) goto yy71;
				goto yy73;
			}
		}
	} else {
		if(yych <= 0xCB) {
			if(yych <= 0xC8) {
				if(yych <= 0xC6) goto yy72;
				if(yych <= 0xC7) goto yy74;
				goto yy76;
			} else {
				if(yych <= 0xC9) goto yy75;
				if(yych <= 0xCA) goto yy77;
				goto yy78;
			}
		} else {
			if(yych <= 0xE2) {
				if(yych <= 0xE0) goto yy19;
				if(yych <= 0xE1) goto yy79;
				goto yy95;
			} else {
				if(yych <= 0xE3) goto yy80;
				if(yych == 0xEF) goto yy81;
				goto yy19;
			}
		}
	}
yy70:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xB4) {
		if(yych == 0xAA) goto yy68;
		goto yy48;
	} else {
		if(yych <= 0xB5) goto yy68;
		if(yych == 0xBA) goto yy68;
		goto yy48;
	}
yy71:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x97) {
		if(yych <= 0x7F) goto yy48;
		if(yych <= 0x96) goto yy68;
		goto yy48;
	} else {
		if(yych == 0xB7) goto yy48;
		if(yych <= 0xBF) goto yy68;
		goto yy48;
	}
yy72:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy68;
	goto yy48;
yy73:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy68;
	goto yy48;
yy74:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy68;
	goto yy48;
yy75:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0x81) goto yy68;
	if(yych <= 0x8F) goto yy48;
	if(yych <= 0xBF) goto yy68;
	goto yy48;
yy76:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy68;
	goto yy48;
yy77:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy68;
	goto yy48;
yy78:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x91) {
		if(yych <= 0x7F) goto yy48;
		if(yych <= 0x81) goto yy68;
		if(yych <= 0x85) goto yy48;
		goto yy68;
	} else {
		if(yych <= 0xA4) {
			if(yych <= 0x9F) goto yy48;
			goto yy68;
		} else {
			if(yych == 0xAE) goto yy68;
			goto yy48;
		}
	}
yy79:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 0xB4:	goto yy92;
	case 0xB5:	goto yy91;
	case 0xB6:	goto yy90;
	case 0xB8:	goto yy89;
	case 0xB9:	goto yy88;
	case 0xBA:	goto yy87;
	case 0xBB:	goto yy86;
	default:	goto yy48;
	}
yy80:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == 0x80) goto yy85;
	goto yy48;
yy81:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xBB) {
		if(yych == 0xAC) goto yy84;
		goto yy48;
	} else {
		if(yych <= 0xBC) goto yy83;
		if(yych >= 0xBE) goto yy48;
	}
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x80) goto yy48;
	if(yych <= 0x9A) goto yy68;
	goto yy48;
yy83:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xA0) goto yy48;
	if(yych <= 0xBA) goto yy68;
	goto yy48;
yy84:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0x86) goto yy68;
	goto yy48;
yy85:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == 0x85) goto yy68;
	if(yych == 0xBB) goto yy68;
	goto yy48;
yy86:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xB9) goto yy68;
	goto yy48;
yy87:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0x9B) goto yy68;
	if(yych <= 0x9F) goto yy48;
	if(yych <= 0xBF) goto yy68;
	goto yy48;
yy88:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy68;
	goto yy48;
yy89:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy68;
	goto yy48;
yy90:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0x9A) goto yy68;
	goto yy48;
yy91:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych == 0xB8) goto yy48;
	if(yych <= 0xBF) goto yy68;
	goto yy48;
yy92:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy68;
	goto yy48;
yy93:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xC7) {
		if(yych <= 0xC1) {
			if(yych <= 'Z') {
				if(yych <= '@') goto yy48;
				goto yy103;
			} else {
				if(yych <= '`') goto yy48;
				if(yych <= 'z') goto yy103;
				goto yy48;
			}
		} else {
			if(yych <= 0xC3) {
				if(yych <= 0xC2) goto yy107;
				goto yy108;
			} else {
				if(yych <= 0xC5) goto yy110;
				if(yych <= 0xC6) goto yy109;
				goto yy111;
			}
		}
	} else {
		if(yych <= 0xE0) {
			if(yych <= 0xC9) {
				if(yych <= 0xC8) goto yy113;
				goto yy112;
			} else {
				if(yych <= 0xCA) goto yy114;
				if(yych <= 0xCB) goto yy115;
				goto yy48;
			}
		} else {
			if(yych <= 0xE3) {
				if(yych <= 0xE1) goto yy116;
				if(yych <= 0xE2) goto yy117;
				goto yy118;
			} else {
				if(yych == 0xEF) goto yy119;
				goto yy48;
			}
		}
	}
yy94:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 0xAA:
	case 0xB5:
	case 0xBA:	goto yy68;
	case 0xB7:	goto yy93;
	default:	goto yy48;
	}
yy95:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x81) {
		if(yych <= 0x7F) goto yy48;
		if(yych <= 0x80) goto yy106;
		goto yy105;
	} else {
		if(yych <= 0x91) goto yy48;
		if(yych <= 0x92) goto yy101;
		if(yych <= 0x93) goto yy100;
		goto yy48;
	}
yy96:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xC2) {
		if(yych <= ':') {
			if(yych <= '-') {
				if(yych != ',') goto yy19;
			} else {
				if(yych <= '.') goto yy98;
				if(yych <= '/') goto yy19;
				if(yych <= '9') goto yy96;
				goto yy19;
			}
		} else {
			if(yych <= 'Z') {
				if(yych <= ';') goto yy98;
				if(yych <= '@') goto yy19;
				goto yy68;
			} else {
				if(yych <= '`') goto yy19;
				if(yych <= 'z') goto yy68;
				if(yych <= 0xC1) goto yy19;
				goto yy70;
			}
		}
	} else {
		if(yych <= 0xCA) {
			if(yych <= 0xC6) {
				if(yych <= 0xC3) goto yy71;
				if(yych <= 0xC5) goto yy73;
				goto yy72;
			} else {
				if(yych <= 0xC7) goto yy74;
				if(yych <= 0xC8) goto yy76;
				if(yych <= 0xC9) goto yy75;
				goto yy77;
			}
		} else {
			if(yych <= 0xE2) {
				if(yych <= 0xCB) goto yy78;
				if(yych <= 0xE0) goto yy19;
				if(yych <= 0xE1) goto yy79;
				goto yy99;
			} else {
				if(yych <= 0xE3) goto yy80;
				if(yych == 0xEF) goto yy81;
				goto yy19;
			}
		}
	}
yy98:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= '/') goto yy48;
	if(yych <= '9') goto yy103;
	goto yy48;
yy99:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x91) {
		if(yych == 0x81) goto yy102;
		goto yy48;
	} else {
		if(yych <= 0x92) goto yy101;
		if(yych >= 0x94) goto yy48;
	}
yy100:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xA9) goto yy68;
	goto yy48;
yy101:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xB5) goto yy48;
	if(yych <= 0xBF) goto yy68;
	goto yy48;
yy102:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xB0) {
		if(yych == 0x84) goto yy98;
		goto yy48;
	} else {
		if(yych <= 0xB1) goto yy68;
		if(yych == 0xBF) goto yy68;
		goto yy48;
	}
yy103:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xC6) {
		if(yych <= '`') {
			if(yych <= '9') {
				if(yych <= '/') goto yy19;
				goto yy96;
			} else {
				if(yych <= '@') goto yy19;
				if(yych <= 'Z') goto yy68;
				goto yy19;
			}
		} else {
			if(yych <= 0xC2) {
				if(yych <= 'z') goto yy68;
				if(yych <= 0xC1) goto yy19;
				goto yy70;
			} else {
				if(yych <= 0xC3) goto yy71;
				if(yych <= 0xC5) goto yy73;
				goto yy72;
			}
		}
	} else {
		if(yych <= 0xE0) {
			if(yych <= 0xC9) {
				if(yych <= 0xC7) goto yy74;
				if(yych <= 0xC8) goto yy76;
				goto yy75;
			} else {
				if(yych <= 0xCA) goto yy77;
				if(yych <= 0xCB) goto yy78;
				goto yy19;
			}
		} else {
			if(yych <= 0xE3) {
				if(yych <= 0xE1) goto yy79;
				if(yych >= 0xE3) goto yy80;
			} else {
				if(yych == 0xEF) goto yy81;
				goto yy19;
			}
		}
	}
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x91) {
		if(yych != 0x81) goto yy48;
	} else {
		if(yych <= 0x92) goto yy101;
		if(yych <= 0x93) goto yy100;
		goto yy48;
	}
yy105:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == 0xB1) goto yy68;
	if(yych == 0xBF) goto yy68;
	goto yy48;
yy106:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == 0x99) goto yy93;
	if(yych == 0xA7) goto yy93;
	goto yy48;
yy107:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xB4) {
		if(yych == 0xAA) goto yy103;
		goto yy48;
	} else {
		if(yych <= 0xB5) goto yy103;
		if(yych == 0xBA) goto yy103;
		goto yy48;
	}
yy108:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x97) {
		if(yych <= 0x7F) goto yy48;
		if(yych <= 0x96) goto yy103;
		goto yy48;
	} else {
		if(yych == 0xB7) goto yy48;
		if(yych <= 0xBF) goto yy103;
		goto yy48;
	}
yy109:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy103;
	goto yy48;
yy110:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy103;
	goto yy48;
yy111:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy103;
	goto yy48;
yy112:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0x81) goto yy103;
	if(yych <= 0x8F) goto yy48;
	if(yych <= 0xBF) goto yy103;
	goto yy48;
yy113:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy103;
	goto yy48;
yy114:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy103;
	goto yy48;
yy115:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x91) {
		if(yych <= 0x7F) goto yy48;
		if(yych <= 0x81) goto yy103;
		if(yych <= 0x85) goto yy48;
		goto yy103;
	} else {
		if(yych <= 0xA4) {
			if(yych <= 0x9F) goto yy48;
			goto yy103;
		} else {
			if(yych == 0xAE) goto yy103;
			goto yy48;
		}
	}
yy116:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 0xB4:	goto yy133;
	case 0xB5:	goto yy132;
	case 0xB6:	goto yy131;
	case 0xB8:	goto yy130;
	case 0xB9:	goto yy129;
	case 0xBA:	goto yy128;
	case 0xBB:	goto yy127;
	default:	goto yy48;
	}
yy117:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x91) {
		if(yych == 0x81) goto yy126;
		goto yy48;
	} else {
		if(yych <= 0x92) goto yy125;
		if(yych <= 0x93) goto yy124;
		goto yy48;
	}
yy118:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == 0x80) goto yy123;
	goto yy48;
yy119:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xBB) {
		if(yych == 0xAC) goto yy122;
		goto yy48;
	} else {
		if(yych <= 0xBC) goto yy121;
		if(yych >= 0xBE) goto yy48;
	}
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x80) goto yy48;
	if(yych <= 0x9A) goto yy103;
	goto yy48;
yy121:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xA0) goto yy48;
	if(yych <= 0xBA) goto yy103;
	goto yy48;
yy122:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0x86) goto yy103;
	goto yy48;
yy123:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == 0x85) goto yy103;
	if(yych == 0xBB) goto yy103;
	goto yy48;
yy124:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xA9) goto yy103;
	goto yy48;
yy125:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xB5) goto yy48;
	if(yych <= 0xBF) goto yy103;
	goto yy48;
yy126:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == 0xB1) goto yy103;
	if(yych == 0xBF) goto yy103;
	goto yy48;
yy127:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xB9) goto yy103;
	goto yy48;
yy128:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0x9B) goto yy103;
	if(yych <= 0x9F) goto yy48;
	if(yych <= 0xBF) goto yy103;
	goto yy48;
yy129:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy103;
	goto yy48;
yy130:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy103;
	goto yy48;
yy131:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0x9A) goto yy103;
	goto yy48;
yy132:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych == 0xB8) goto yy48;
	if(yych <= 0xBF) goto yy103;
	goto yy48;
yy133:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy103;
	goto yy48;
yy134:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xB0) {
		if(yych == 0x84) goto yy64;
		goto yy48;
	} else {
		if(yych <= 0xB1) goto yy68;
		if(yych == 0xBF) goto yy68;
		goto yy48;
	}
yy135:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	if((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	if(yych <= 0xC2) {
		if(yych <= ':') {
			if(yych <= '-') {
				if(yych == ',') goto yy137;
				goto yy19;
			} else {
				if(yych <= '.') goto yy137;
				if(yych <= '/') goto yy19;
				if(yych <= '9') goto yy66;
				goto yy19;
			}
		} else {
			if(yych <= 'Z') {
				if(yych <= ';') goto yy137;
				if(yych <= '@') goto yy19;
				goto yy68;
			} else {
				if(yych <= '`') goto yy19;
				if(yych <= 'z') goto yy68;
				if(yych <= 0xC1) goto yy19;
				goto yy70;
			}
		}
	} else {
		if(yych <= 0xCA) {
			if(yych <= 0xC6) {
				if(yych <= 0xC3) goto yy71;
				if(yych <= 0xC5) goto yy73;
				goto yy72;
			} else {
				if(yych <= 0xC7) goto yy74;
				if(yych <= 0xC8) goto yy76;
				if(yych <= 0xC9) goto yy75;
				goto yy77;
			}
		} else {
			if(yych <= 0xE2) {
				if(yych <= 0xCB) goto yy78;
				if(yych <= 0xE0) goto yy19;
				if(yych <= 0xE1) goto yy79;
			} else {
				if(yych <= 0xE3) goto yy80;
				if(yych == 0xEF) goto yy81;
				goto yy19;
			}
		}
	}
	yych = *++YYCURSOR;
	if(yych <= 0x91) {
		if(yych == 0x81) goto yy142;
		goto yy48;
	} else {
		if(yych <= 0x92) goto yy101;
		if(yych <= 0x93) goto yy100;
		goto yy48;
	}
yy137:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= '/') goto yy48;
	if(yych >= ':') goto yy48;
yy138:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= '/') {
		if(yych <= ',') {
			if(yych <= '+') goto yy19;
			goto yy137;
		} else {
			if(yych == '.') goto yy137;
			goto yy19;
		}
	} else {
		if(yych <= ';') {
			if(yych <= '9') goto yy138;
			if(yych <= ':') goto yy19;
			goto yy137;
		} else {
			if(yych != 0xE2) goto yy19;
		}
	}
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych != 0x81) goto yy48;
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == 0x84) goto yy137;
	goto yy48;
yy142:
	yych = *++YYCURSOR;
	if(yych <= 0xB0) {
		if(yych == 0x84) goto yy137;
		goto yy48;
	} else {
		if(yych <= 0xB1) goto yy68;
		if(yych == 0xBF) goto yy68;
		goto yy48;
	}
yy143:
	yych = *++YYCURSOR;
	if(yych <= 0x85) {
		if(yych <= 0x7F) goto yy48;
		if(yych <= 0x84) goto yy50;
	} else {
		if(yych == 0xBB) goto yy144;
		if(yych <= 0xBF) goto yy50;
		goto yy48;
	}
yy144:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= '.') {
		if(yych <= '+') {
			if(yych != '\'') goto yy149;
		} else {
			if(yych == '-') goto yy149;
			goto yy19;
		}
	} else {
		if(yych <= 0xC1) {
			if(yych == ';') goto yy19;
			goto yy149;
		} else {
			if(yych <= 0xC2) goto yy146;
			if(yych == 0xE2) goto yy147;
			goto yy149;
		}
	}
yy145:
	yych = *++YYCURSOR;
	if(yych <= 0xC7) {
		if(yych <= 0xC1) {
			if(yych <= 'Z') {
				if(yych <= '@') goto yy48;
				goto yy214;
			} else {
				if(yych <= '`') goto yy48;
				if(yych <= 'z') goto yy214;
				goto yy48;
			}
		} else {
			if(yych <= 0xC3) {
				if(yych <= 0xC2) goto yy215;
				goto yy216;
			} else {
				if(yych <= 0xC5) goto yy218;
				if(yych <= 0xC6) goto yy217;
				goto yy219;
			}
		}
	} else {
		if(yych <= 0xE0) {
			if(yych <= 0xC9) {
				if(yych <= 0xC8) goto yy221;
				goto yy220;
			} else {
				if(yych <= 0xCA) goto yy222;
				if(yych <= 0xCB) goto yy223;
				goto yy48;
			}
		} else {
			if(yych <= 0xE3) {
				if(yych <= 0xE1) goto yy224;
				if(yych <= 0xE2) goto yy225;
				goto yy226;
			} else {
				if(yych == 0xEF) goto yy227;
				goto yy48;
			}
		}
	}
yy146:
	yych = *++YYCURSOR;
	switch(yych) {
	case 0xAA:
	case 0xB5:
	case 0xBA:	goto yy150;
	case 0xB7:	goto yy145;
	default:	goto yy48;
	}
yy147:
	yych = *++YYCURSOR;
	if(yych <= 0x81) {
		if(yych <= 0x7F) goto yy48;
		if(yych <= 0x80) goto yy213;
		goto yy179;
	} else {
		if(yych <= 0x91) goto yy48;
		if(yych <= 0x92) goto yy178;
		if(yych <= 0x93) goto yy177;
		goto yy48;
	}
yy148:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy149:
	if(yych <= 0xC2) {
		if(yych <= ':') {
			if(yych <= '-') {
				if(yych == ',') goto yy98;
				goto yy19;
			} else {
				if(yych <= '.') goto yy98;
				if(yych <= '/') goto yy19;
				if(yych <= '9') goto yy148;
				goto yy19;
			}
		} else {
			if(yych <= 'Z') {
				if(yych <= ';') goto yy98;
				if(yych <= '@') goto yy19;
			} else {
				if(yych <= '`') goto yy19;
				if(yych <= 'z') goto yy150;
				if(yych <= 0xC1) goto yy19;
				goto yy209;
			}
		}
	} else {
		if(yych <= 0xCA) {
			if(yych <= 0xC6) {
				if(yych <= 0xC3) goto yy152;
				if(yych <= 0xC5) goto yy154;
				goto yy153;
			} else {
				if(yych <= 0xC7) goto yy155;
				if(yych <= 0xC8) goto yy157;
				if(yych <= 0xC9) goto yy156;
				goto yy158;
			}
		} else {
			if(yych <= 0xE2) {
				if(yych <= 0xCB) goto yy159;
				if(yych <= 0xE0) goto yy19;
				if(yych <= 0xE1) goto yy160;
				goto yy211;
			} else {
				if(yych <= 0xE3) goto yy161;
				if(yych == 0xEF) goto yy162;
				goto yy19;
			}
		}
	}
yy150:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xC5) {
		if(yych <= 'Z') {
			if(yych <= '/') {
				if(yych == '\'') goto yy174;
				goto yy19;
			} else {
				if(yych <= '9') goto yy148;
				if(yych <= '@') goto yy19;
				goto yy150;
			}
		} else {
			if(yych <= 0xC1) {
				if(yych <= '`') goto yy19;
				if(yych <= 'z') goto yy150;
				goto yy19;
			} else {
				if(yych <= 0xC2) goto yy175;
				if(yych >= 0xC4) goto yy154;
			}
		}
	} else {
		if(yych <= 0xCB) {
			if(yych <= 0xC8) {
				if(yych <= 0xC6) goto yy153;
				if(yych <= 0xC7) goto yy155;
				goto yy157;
			} else {
				if(yych <= 0xC9) goto yy156;
				if(yych <= 0xCA) goto yy158;
				goto yy159;
			}
		} else {
			if(yych <= 0xE2) {
				if(yych <= 0xE0) goto yy19;
				if(yych <= 0xE1) goto yy160;
				goto yy176;
			} else {
				if(yych <= 0xE3) goto yy161;
				if(yych == 0xEF) goto yy162;
				goto yy19;
			}
		}
	}
yy152:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x97) {
		if(yych <= 0x7F) goto yy48;
		if(yych <= 0x96) goto yy150;
		goto yy48;
	} else {
		if(yych == 0xB7) goto yy48;
		if(yych <= 0xBF) goto yy150;
		goto yy48;
	}
yy153:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy150;
	goto yy48;
yy154:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy150;
	goto yy48;
yy155:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy150;
	goto yy48;
yy156:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0x81) goto yy150;
	if(yych <= 0x8F) goto yy48;
	if(yych <= 0xBF) goto yy150;
	goto yy48;
yy157:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy150;
	goto yy48;
yy158:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy150;
	goto yy48;
yy159:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x91) {
		if(yych <= 0x7F) goto yy48;
		if(yych <= 0x81) goto yy150;
		if(yych <= 0x85) goto yy48;
		goto yy150;
	} else {
		if(yych <= 0xA4) {
			if(yych <= 0x9F) goto yy48;
			goto yy150;
		} else {
			if(yych == 0xAE) goto yy150;
			goto yy48;
		}
	}
yy160:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 0xB4:	goto yy173;
	case 0xB5:	goto yy172;
	case 0xB6:	goto yy171;
	case 0xB8:	goto yy170;
	case 0xB9:	goto yy169;
	case 0xBA:	goto yy168;
	case 0xBB:	goto yy167;
	default:	goto yy48;
	}
yy161:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == 0x80) goto yy166;
	goto yy48;
yy162:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xBB) {
		if(yych == 0xAC) goto yy165;
		goto yy48;
	} else {
		if(yych <= 0xBC) goto yy164;
		if(yych >= 0xBE) goto yy48;
	}
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x80) goto yy48;
	if(yych <= 0x9A) goto yy150;
	goto yy48;
yy164:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xA0) goto yy48;
	if(yych <= 0xBA) goto yy150;
	goto yy48;
yy165:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0x86) goto yy150;
	goto yy48;
yy166:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == 0x85) goto yy150;
	if(yych == 0xBB) goto yy150;
	goto yy48;
yy167:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xB9) goto yy150;
	goto yy48;
yy168:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0x9B) goto yy150;
	if(yych <= 0x9F) goto yy48;
	if(yych <= 0xBF) goto yy150;
	goto yy48;
yy169:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy150;
	goto yy48;
yy170:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy150;
	goto yy48;
yy171:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0x9A) goto yy150;
	goto yy48;
yy172:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych == 0xB8) goto yy48;
	if(yych <= 0xBF) goto yy150;
	goto yy48;
yy173:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy150;
	goto yy48;
yy174:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xC7) {
		if(yych <= 0xC1) {
			if(yych <= 'Z') {
				if(yych <= '@') goto yy48;
				goto yy181;
			} else {
				if(yych <= '`') goto yy48;
				if(yych <= 'z') goto yy181;
				goto yy48;
			}
		} else {
			if(yych <= 0xC3) {
				if(yych <= 0xC2) goto yy182;
				goto yy183;
			} else {
				if(yych <= 0xC5) goto yy185;
				if(yych <= 0xC6) goto yy184;
				goto yy186;
			}
		}
	} else {
		if(yych <= 0xE0) {
			if(yych <= 0xC9) {
				if(yych <= 0xC8) goto yy188;
				goto yy187;
			} else {
				if(yych <= 0xCA) goto yy189;
				if(yych <= 0xCB) goto yy190;
				goto yy48;
			}
		} else {
			if(yych <= 0xE3) {
				if(yych <= 0xE1) goto yy191;
				if(yych <= 0xE2) goto yy192;
				goto yy193;
			} else {
				if(yych == 0xEF) goto yy194;
				goto yy48;
			}
		}
	}
yy175:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 0xAA:
	case 0xB5:
	case 0xBA:	goto yy150;
	case 0xB7:	goto yy174;
	default:	goto yy48;
	}
yy176:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x81) {
		if(yych <= 0x7F) goto yy48;
		if(yych <= 0x80) goto yy180;
		goto yy179;
	} else {
		if(yych <= 0x91) goto yy48;
		if(yych <= 0x92) goto yy178;
		if(yych >= 0x94) goto yy48;
	}
yy177:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xA9) goto yy150;
	goto yy48;
yy178:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xB5) goto yy48;
	if(yych <= 0xBF) goto yy150;
	goto yy48;
yy179:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == 0xB1) goto yy150;
	if(yych == 0xBF) goto yy150;
	goto yy48;
yy180:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == 0x99) goto yy174;
	if(yych == 0xA7) goto yy174;
	goto yy48;
yy181:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xC6) {
		if(yych <= '`') {
			if(yych <= '9') {
				if(yych <= '/') goto yy19;
				goto yy148;
			} else {
				if(yych <= '@') goto yy19;
				if(yych <= 'Z') goto yy150;
				goto yy19;
			}
		} else {
			if(yych <= 0xC2) {
				if(yych <= 'z') goto yy150;
				if(yych <= 0xC1) goto yy19;
				goto yy209;
			} else {
				if(yych <= 0xC3) goto yy152;
				if(yych <= 0xC5) goto yy154;
				goto yy153;
			}
		}
	} else {
		if(yych <= 0xE0) {
			if(yych <= 0xC9) {
				if(yych <= 0xC7) goto yy155;
				if(yych <= 0xC8) goto yy157;
				goto yy156;
			} else {
				if(yych <= 0xCA) goto yy158;
				if(yych <= 0xCB) goto yy159;
				goto yy19;
			}
		} else {
			if(yych <= 0xE3) {
				if(yych <= 0xE1) goto yy160;
				if(yych <= 0xE2) goto yy210;
				goto yy161;
			} else {
				if(yych == 0xEF) goto yy162;
				goto yy19;
			}
		}
	}
yy182:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xB4) {
		if(yych == 0xAA) goto yy181;
		goto yy48;
	} else {
		if(yych <= 0xB5) goto yy181;
		if(yych == 0xBA) goto yy181;
		goto yy48;
	}
yy183:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x97) {
		if(yych <= 0x7F) goto yy48;
		if(yych <= 0x96) goto yy181;
		goto yy48;
	} else {
		if(yych == 0xB7) goto yy48;
		if(yych <= 0xBF) goto yy181;
		goto yy48;
	}
yy184:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy181;
	goto yy48;
yy185:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy181;
	goto yy48;
yy186:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy181;
	goto yy48;
yy187:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0x81) goto yy181;
	if(yych <= 0x8F) goto yy48;
	if(yych <= 0xBF) goto yy181;
	goto yy48;
yy188:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy181;
	goto yy48;
yy189:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy181;
	goto yy48;
yy190:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x91) {
		if(yych <= 0x7F) goto yy48;
		if(yych <= 0x81) goto yy181;
		if(yych <= 0x85) goto yy48;
		goto yy181;
	} else {
		if(yych <= 0xA4) {
			if(yych <= 0x9F) goto yy48;
			goto yy181;
		} else {
			if(yych == 0xAE) goto yy181;
			goto yy48;
		}
	}
yy191:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 0xB4:	goto yy208;
	case 0xB5:	goto yy207;
	case 0xB6:	goto yy206;
	case 0xB8:	goto yy205;
	case 0xB9:	goto yy204;
	case 0xBA:	goto yy203;
	case 0xBB:	goto yy202;
	default:	goto yy48;
	}
yy192:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x91) {
		if(yych == 0x81) goto yy201;
		goto yy48;
	} else {
		if(yych <= 0x92) goto yy200;
		if(yych <= 0x93) goto yy199;
		goto yy48;
	}
yy193:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == 0x80) goto yy198;
	goto yy48;
yy194:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xBB) {
		if(yych == 0xAC) goto yy197;
		goto yy48;
	} else {
		if(yych <= 0xBC) goto yy196;
		if(yych >= 0xBE) goto yy48;
	}
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x80) goto yy48;
	if(yych <= 0x9A) goto yy181;
	goto yy48;
yy196:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xA0) goto yy48;
	if(yych <= 0xBA) goto yy181;
	goto yy48;
yy197:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0x86) goto yy181;
	goto yy48;
yy198:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == 0x85) goto yy181;
	if(yych == 0xBB) goto yy181;
	goto yy48;
yy199:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xA9) goto yy181;
	goto yy48;
yy200:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xB5) goto yy48;
	if(yych <= 0xBF) goto yy181;
	goto yy48;
yy201:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == 0xB1) goto yy181;
	if(yych == 0xBF) goto yy181;
	goto yy48;
yy202:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xB9) goto yy181;
	goto yy48;
yy203:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0x9B) goto yy181;
	if(yych <= 0x9F) goto yy48;
	if(yych <= 0xBF) goto yy181;
	goto yy48;
yy204:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy181;
	goto yy48;
yy205:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy181;
	goto yy48;
yy206:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0x9A) goto yy181;
	goto yy48;
yy207:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych == 0xB8) goto yy48;
	if(yych <= 0xBF) goto yy181;
	goto yy48;
yy208:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy181;
	goto yy48;
yy209:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xB4) {
		if(yych == 0xAA) goto yy150;
		goto yy48;
	} else {
		if(yych <= 0xB5) goto yy150;
		if(yych == 0xBA) goto yy150;
		goto yy48;
	}
yy210:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x91) {
		if(yych == 0x81) goto yy179;
		goto yy48;
	} else {
		if(yych <= 0x92) goto yy178;
		if(yych <= 0x93) goto yy177;
		goto yy48;
	}
yy211:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x91) {
		if(yych != 0x81) goto yy48;
	} else {
		if(yych <= 0x92) goto yy178;
		if(yych <= 0x93) goto yy177;
		goto yy48;
	}
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xB0) {
		if(yych == 0x84) goto yy98;
		goto yy48;
	} else {
		if(yych <= 0xB1) goto yy150;
		if(yych == 0xBF) goto yy150;
		goto yy48;
	}
yy213:
	yych = *++YYCURSOR;
	if(yych == 0x99) goto yy145;
	if(yych == 0xA7) goto yy145;
	goto yy48;
yy214:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xC6) {
		if(yych <= '`') {
			if(yych <= '9') {
				if(yych <= '/') goto yy19;
				goto yy242;
			} else {
				if(yych <= '@') goto yy19;
				if(yych <= 'Z') goto yy244;
				goto yy19;
			}
		} else {
			if(yych <= 0xC2) {
				if(yych <= 'z') goto yy244;
				if(yych <= 0xC1) goto yy19;
				goto yy246;
			} else {
				if(yych <= 0xC3) goto yy247;
				if(yych <= 0xC5) goto yy249;
				goto yy248;
			}
		}
	} else {
		if(yych <= 0xE0) {
			if(yych <= 0xC9) {
				if(yych <= 0xC7) goto yy250;
				if(yych <= 0xC8) goto yy252;
				goto yy251;
			} else {
				if(yych <= 0xCA) goto yy253;
				if(yych <= 0xCB) goto yy254;
				goto yy19;
			}
		} else {
			if(yych <= 0xE3) {
				if(yych <= 0xE1) goto yy255;
				if(yych <= 0xE2) goto yy256;
				goto yy257;
			} else {
				if(yych == 0xEF) goto yy258;
				goto yy19;
			}
		}
	}
yy215:
	yych = *++YYCURSOR;
	if(yych <= 0xB4) {
		if(yych == 0xAA) goto yy214;
		goto yy48;
	} else {
		if(yych <= 0xB5) goto yy214;
		if(yych == 0xBA) goto yy214;
		goto yy48;
	}
yy216:
	yych = *++YYCURSOR;
	if(yych <= 0x97) {
		if(yych <= 0x7F) goto yy48;
		if(yych <= 0x96) goto yy214;
		goto yy48;
	} else {
		if(yych == 0xB7) goto yy48;
		if(yych <= 0xBF) goto yy214;
		goto yy48;
	}
yy217:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy214;
	goto yy48;
yy218:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy214;
	goto yy48;
yy219:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy214;
	goto yy48;
yy220:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0x81) goto yy214;
	if(yych <= 0x8F) goto yy48;
	if(yych <= 0xBF) goto yy214;
	goto yy48;
yy221:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy214;
	goto yy48;
yy222:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy214;
	goto yy48;
yy223:
	yych = *++YYCURSOR;
	if(yych <= 0x91) {
		if(yych <= 0x7F) goto yy48;
		if(yych <= 0x81) goto yy214;
		if(yych <= 0x85) goto yy48;
		goto yy214;
	} else {
		if(yych <= 0xA4) {
			if(yych <= 0x9F) goto yy48;
			goto yy214;
		} else {
			if(yych == 0xAE) goto yy214;
			goto yy48;
		}
	}
yy224:
	yych = *++YYCURSOR;
	switch(yych) {
	case 0xB4:	goto yy241;
	case 0xB5:	goto yy240;
	case 0xB6:	goto yy239;
	case 0xB8:	goto yy238;
	case 0xB9:	goto yy237;
	case 0xBA:	goto yy236;
	case 0xBB:	goto yy235;
	default:	goto yy48;
	}
yy225:
	yych = *++YYCURSOR;
	if(yych <= 0x91) {
		if(yych == 0x81) goto yy234;
		goto yy48;
	} else {
		if(yych <= 0x92) goto yy233;
		if(yych <= 0x93) goto yy232;
		goto yy48;
	}
yy226:
	yych = *++YYCURSOR;
	if(yych == 0x80) goto yy231;
	goto yy48;
yy227:
	yych = *++YYCURSOR;
	if(yych <= 0xBB) {
		if(yych == 0xAC) goto yy230;
		goto yy48;
	} else {
		if(yych <= 0xBC) goto yy229;
		if(yych >= 0xBE) goto yy48;
	}
	yych = *++YYCURSOR;
	if(yych <= 0x80) goto yy48;
	if(yych <= 0x9A) goto yy214;
	goto yy48;
yy229:
	yych = *++YYCURSOR;
	if(yych <= 0xA0) goto yy48;
	if(yych <= 0xBA) goto yy214;
	goto yy48;
yy230:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0x86) goto yy214;
	goto yy48;
yy231:
	yych = *++YYCURSOR;
	if(yych == 0x85) goto yy214;
	if(yych == 0xBB) goto yy214;
	goto yy48;
yy232:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xA9) goto yy214;
	goto yy48;
yy233:
	yych = *++YYCURSOR;
	if(yych <= 0xB5) goto yy48;
	if(yych <= 0xBF) goto yy214;
	goto yy48;
yy234:
	yych = *++YYCURSOR;
	if(yych == 0xB1) goto yy214;
	if(yych == 0xBF) goto yy214;
	goto yy48;
yy235:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xB9) goto yy214;
	goto yy48;
yy236:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0x9B) goto yy214;
	if(yych <= 0x9F) goto yy48;
	if(yych <= 0xBF) goto yy214;
	goto yy48;
yy237:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy214;
	goto yy48;
yy238:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy214;
	goto yy48;
yy239:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0x9A) goto yy214;
	goto yy48;
yy240:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych == 0xB8) goto yy48;
	if(yych <= 0xBF) goto yy214;
	goto yy48;
yy241:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy214;
	goto yy48;
yy242:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xC2) {
		if(yych <= ':') {
			if(yych <= '-') {
				if(yych == ',') goto yy98;
				goto yy19;
			} else {
				if(yych <= '.') goto yy98;
				if(yych <= '/') goto yy19;
				if(yych <= '9') goto yy242;
				goto yy19;
			}
		} else {
			if(yych <= 'Z') {
				if(yych <= ';') goto yy98;
				if(yych <= '@') goto yy19;
			} else {
				if(yych <= '`') goto yy19;
				if(yych <= 'z') goto yy244;
				if(yych <= 0xC1) goto yy19;
				goto yy246;
			}
		}
	} else {
		if(yych <= 0xCA) {
			if(yych <= 0xC6) {
				if(yych <= 0xC3) goto yy247;
				if(yych <= 0xC5) goto yy249;
				goto yy248;
			} else {
				if(yych <= 0xC7) goto yy250;
				if(yych <= 0xC8) goto yy252;
				if(yych <= 0xC9) goto yy251;
				goto yy253;
			}
		} else {
			if(yych <= 0xE2) {
				if(yych <= 0xCB) goto yy254;
				if(yych <= 0xE0) goto yy19;
				if(yych <= 0xE1) goto yy255;
				goto yy304;
			} else {
				if(yych <= 0xE3) goto yy257;
				if(yych == 0xEF) goto yy258;
				goto yy19;
			}
		}
	}
yy244:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xC5) {
		if(yych <= 'Z') {
			if(yych <= '/') {
				if(yych == '\'') goto yy273;
				goto yy19;
			} else {
				if(yych <= '9') goto yy242;
				if(yych <= '@') goto yy19;
				goto yy244;
			}
		} else {
			if(yych <= 0xC1) {
				if(yych <= '`') goto yy19;
				if(yych <= 'z') goto yy244;
				goto yy19;
			} else {
				if(yych <= 0xC2) goto yy274;
				if(yych <= 0xC3) goto yy247;
				goto yy249;
			}
		}
	} else {
		if(yych <= 0xCB) {
			if(yych <= 0xC8) {
				if(yych <= 0xC6) goto yy248;
				if(yych <= 0xC7) goto yy250;
				goto yy252;
			} else {
				if(yych <= 0xC9) goto yy251;
				if(yych <= 0xCA) goto yy253;
				goto yy254;
			}
		} else {
			if(yych <= 0xE2) {
				if(yych <= 0xE0) goto yy19;
				if(yych <= 0xE1) goto yy255;
				goto yy275;
			} else {
				if(yych <= 0xE3) goto yy257;
				if(yych == 0xEF) goto yy258;
				goto yy19;
			}
		}
	}
yy246:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xB4) {
		if(yych == 0xAA) goto yy244;
		goto yy48;
	} else {
		if(yych <= 0xB5) goto yy244;
		if(yych == 0xBA) goto yy244;
		goto yy48;
	}
yy247:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x97) {
		if(yych <= 0x7F) goto yy48;
		if(yych <= 0x96) goto yy244;
		goto yy48;
	} else {
		if(yych == 0xB7) goto yy48;
		if(yych <= 0xBF) goto yy244;
		goto yy48;
	}
yy248:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy244;
	goto yy48;
yy249:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy244;
	goto yy48;
yy250:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy244;
	goto yy48;
yy251:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0x81) goto yy244;
	if(yych <= 0x8F) goto yy48;
	if(yych <= 0xBF) goto yy244;
	goto yy48;
yy252:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy244;
	goto yy48;
yy253:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy244;
	goto yy48;
yy254:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x91) {
		if(yych <= 0x7F) goto yy48;
		if(yych <= 0x81) goto yy244;
		if(yych <= 0x85) goto yy48;
		goto yy244;
	} else {
		if(yych <= 0xA4) {
			if(yych <= 0x9F) goto yy48;
			goto yy244;
		} else {
			if(yych == 0xAE) goto yy244;
			goto yy48;
		}
	}
yy255:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 0xB4:	goto yy272;
	case 0xB5:	goto yy271;
	case 0xB6:	goto yy270;
	case 0xB8:	goto yy269;
	case 0xB9:	goto yy268;
	case 0xBA:	goto yy267;
	case 0xBB:	goto yy266;
	default:	goto yy48;
	}
yy256:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x91) {
		if(yych == 0x81) goto yy265;
		goto yy48;
	} else {
		if(yych <= 0x92) goto yy264;
		if(yych <= 0x93) goto yy263;
		goto yy48;
	}
yy257:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == 0x80) goto yy262;
	goto yy48;
yy258:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xBB) {
		if(yych == 0xAC) goto yy261;
		goto yy48;
	} else {
		if(yych <= 0xBC) goto yy260;
		if(yych >= 0xBE) goto yy48;
	}
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x80) goto yy48;
	if(yych <= 0x9A) goto yy244;
	goto yy48;
yy260:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xA0) goto yy48;
	if(yych <= 0xBA) goto yy244;
	goto yy48;
yy261:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0x86) goto yy244;
	goto yy48;
yy262:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == 0x85) goto yy244;
	if(yych == 0xBB) goto yy244;
	goto yy48;
yy263:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xA9) goto yy244;
	goto yy48;
yy264:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xB5) goto yy48;
	if(yych <= 0xBF) goto yy244;
	goto yy48;
yy265:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == 0xB1) goto yy244;
	if(yych == 0xBF) goto yy244;
	goto yy48;
yy266:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xB9) goto yy244;
	goto yy48;
yy267:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0x9B) goto yy244;
	if(yych <= 0x9F) goto yy48;
	if(yych <= 0xBF) goto yy244;
	goto yy48;
yy268:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy244;
	goto yy48;
yy269:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy244;
	goto yy48;
yy270:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0x9A) goto yy244;
	goto yy48;
yy271:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych == 0xB8) goto yy48;
	if(yych <= 0xBF) goto yy244;
	goto yy48;
yy272:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy244;
	goto yy48;
yy273:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xC7) {
		if(yych <= 0xC1) {
			if(yych <= 'Z') {
				if(yych <= '@') goto yy48;
				goto yy214;
			} else {
				if(yych <= '`') goto yy48;
				if(yych <= 'z') goto yy214;
				goto yy48;
			}
		} else {
			if(yych <= 0xC3) {
				if(yych <= 0xC2) goto yy277;
				goto yy278;
			} else {
				if(yych <= 0xC5) goto yy280;
				if(yych <= 0xC6) goto yy279;
				goto yy281;
			}
		}
	} else {
		if(yych <= 0xE0) {
			if(yych <= 0xC9) {
				if(yych <= 0xC8) goto yy283;
				goto yy282;
			} else {
				if(yych <= 0xCA) goto yy284;
				if(yych <= 0xCB) goto yy285;
				goto yy48;
			}
		} else {
			if(yych <= 0xE3) {
				if(yych <= 0xE1) goto yy286;
				if(yych <= 0xE2) goto yy287;
				goto yy288;
			} else {
				if(yych == 0xEF) goto yy289;
				goto yy48;
			}
		}
	}
yy274:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 0xAA:
	case 0xB5:
	case 0xBA:	goto yy244;
	case 0xB7:	goto yy273;
	default:	goto yy48;
	}
yy275:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x81) {
		if(yych <= 0x7F) goto yy48;
		if(yych >= 0x81) goto yy265;
	} else {
		if(yych <= 0x91) goto yy48;
		if(yych <= 0x92) goto yy264;
		if(yych <= 0x93) goto yy263;
		goto yy48;
	}
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == 0x99) goto yy273;
	if(yych == 0xA7) goto yy273;
	goto yy48;
yy277:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xB4) {
		if(yych == 0xAA) goto yy214;
		goto yy48;
	} else {
		if(yych <= 0xB5) goto yy214;
		if(yych == 0xBA) goto yy214;
		goto yy48;
	}
yy278:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x97) {
		if(yych <= 0x7F) goto yy48;
		if(yych <= 0x96) goto yy214;
		goto yy48;
	} else {
		if(yych == 0xB7) goto yy48;
		if(yych <= 0xBF) goto yy214;
		goto yy48;
	}
yy279:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy214;
	goto yy48;
yy280:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy214;
	goto yy48;
yy281:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy214;
	goto yy48;
yy282:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0x81) goto yy214;
	if(yych <= 0x8F) goto yy48;
	if(yych <= 0xBF) goto yy214;
	goto yy48;
yy283:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy214;
	goto yy48;
yy284:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy214;
	goto yy48;
yy285:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x91) {
		if(yych <= 0x7F) goto yy48;
		if(yych <= 0x81) goto yy214;
		if(yych <= 0x85) goto yy48;
		goto yy214;
	} else {
		if(yych <= 0xA4) {
			if(yych <= 0x9F) goto yy48;
			goto yy214;
		} else {
			if(yych == 0xAE) goto yy214;
			goto yy48;
		}
	}
yy286:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 0xB4:	goto yy303;
	case 0xB5:	goto yy302;
	case 0xB6:	goto yy301;
	case 0xB8:	goto yy300;
	case 0xB9:	goto yy299;
	case 0xBA:	goto yy298;
	case 0xBB:	goto yy297;
	default:	goto yy48;
	}
yy287:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x91) {
		if(yych == 0x81) goto yy296;
		goto yy48;
	} else {
		if(yych <= 0x92) goto yy295;
		if(yych <= 0x93) goto yy294;
		goto yy48;
	}
yy288:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == 0x80) goto yy293;
	goto yy48;
yy289:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xBB) {
		if(yych == 0xAC) goto yy292;
		goto yy48;
	} else {
		if(yych <= 0xBC) goto yy291;
		if(yych >= 0xBE) goto yy48;
	}
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x80) goto yy48;
	if(yych <= 0x9A) goto yy214;
	goto yy48;
yy291:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xA0) goto yy48;
	if(yych <= 0xBA) goto yy214;
	goto yy48;
yy292:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0x86) goto yy214;
	goto yy48;
yy293:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == 0x85) goto yy214;
	if(yych == 0xBB) goto yy214;
	goto yy48;
yy294:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xA9) goto yy214;
	goto yy48;
yy295:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xB5) goto yy48;
	if(yych <= 0xBF) goto yy214;
	goto yy48;
yy296:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == 0xB1) goto yy214;
	if(yych == 0xBF) goto yy214;
	goto yy48;
yy297:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xB9) goto yy214;
	goto yy48;
yy298:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0x9B) goto yy214;
	if(yych <= 0x9F) goto yy48;
	if(yych <= 0xBF) goto yy214;
	goto yy48;
yy299:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy214;
	goto yy48;
yy300:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy214;
	goto yy48;
yy301:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0x9A) goto yy214;
	goto yy48;
yy302:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych == 0xB8) goto yy48;
	if(yych <= 0xBF) goto yy214;
	goto yy48;
yy303:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy214;
	goto yy48;
yy304:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0x91) {
		if(yych != 0x81) goto yy48;
	} else {
		if(yych <= 0x92) goto yy264;
		if(yych <= 0x93) goto yy263;
		goto yy48;
	}
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 0xB0) {
		if(yych == 0x84) goto yy98;
		goto yy48;
	} else {
		if(yych <= 0xB1) goto yy244;
		if(yych == 0xBF) goto yy244;
		goto yy48;
	}
yy306:
	yych = *++YYCURSOR;
	if(yych <= 0x97) {
		if(yych <= 0x7F) goto yy48;
		if(yych <= 0x8F) goto yy50;
		if(yych <= 0x95) goto yy310;
		goto yy50;
	} else {
		if(yych <= 0xA3) {
			if(yych <= 0x9F) goto yy310;
			goto yy50;
		} else {
			if(yych <= 0xA7) goto yy310;
			if(yych <= 0xBF) goto yy50;
			goto yy48;
		}
	}
yy307:
	yych = *++YYCURSOR;
	if(yych <= 0xB1) {
		if(yych <= 0x7F) goto yy48;
		if(yych <= 0xB0) goto yy50;
		goto yy144;
	} else {
		if(yych <= 0xBE) goto yy50;
		if(yych <= 0xBF) goto yy144;
		goto yy48;
	}
yy308:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xB5) goto yy50;
	if(yych <= 0xBF) goto yy144;
	goto yy48;
yy309:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xA9) goto yy144;
	if(yych <= 0xBF) goto yy50;
	goto yy48;
yy310:
	yych = *++YYCURSOR;
	goto yy39;
yy311:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy144;
	goto yy48;
yy312:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych == 0xB8) goto yy50;
	if(yych <= 0xBF) goto yy144;
	goto yy48;
yy313:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0x9A) goto yy144;
	if(yych <= 0xBF) goto yy50;
	goto yy48;
yy314:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy144;
	goto yy48;
yy315:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBF) goto yy144;
	goto yy48;
yy316:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0x9B) goto yy144;
	if(yych <= 0x9F) goto yy50;
	if(yych <= 0xBF) goto yy144;
	goto yy48;
yy317:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xB9) goto yy144;
	if(yych <= 0xBF) goto yy50;
	goto yy48;
yy318:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	goto yy62;
yy319:
	yych = *++YYCURSOR;
	if(yych == '/') goto yy322;
	goto yy48;
yy320:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	if((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	if(yych <= 0xC5) {
		if(yych <= '@') {
			if(yych <= '/') {
				if(yych == '\'') goto yy174;
				goto yy19;
			} else {
				if(yych <= '9') goto yy148;
				if(yych <= ':') goto yy319;
				goto yy19;
			}
		} else {
			if(yych <= 'z') {
				if(yych <= 'Z') goto yy150;
				if(yych <= '`') goto yy19;
				goto yy320;
			} else {
				if(yych <= 0xC1) goto yy19;
				if(yych <= 0xC2) goto yy175;
				if(yych <= 0xC3) goto yy152;
				goto yy154;
			}
		}
	} else {
		if(yych <= 0xCB) {
			if(yych <= 0xC8) {
				if(yych <= 0xC6) goto yy153;
				if(yych <= 0xC7) goto yy155;
				goto yy157;
			} else {
				if(yych <= 0xC9) goto yy156;
				if(yych <= 0xCA) goto yy158;
				goto yy159;
			}
		} else {
			if(yych <= 0xE2) {
				if(yych <= 0xE0) goto yy19;
				if(yych <= 0xE1) goto yy160;
				goto yy176;
			} else {
				if(yych <= 0xE3) goto yy161;
				if(yych == 0xEF) goto yy162;
				goto yy19;
			}
		}
	}
yy322:
	yych = *++YYCURSOR;
	if(yych != '/') goto yy48;
yy323:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= '@') {
		if(yych <= '+') {
			if(yych <= '#') {
				if(yych <= ' ') goto yy48;
				goto yy323;
			} else {
				if(yych <= '$') goto yy325;
				if(yych <= '*') goto yy323;
			}
		} else {
			if(yych <= ';') {
				if(yych <= '.') goto yy323;
				if(yych >= ':') goto yy323;
			} else {
				if(yych <= '<') goto yy48;
				if(yych >= '?') goto yy323;
			}
		}
	} else {
		if(yych <= '_') {
			if(yych <= '\\') {
				if(yych == '[') goto yy323;
			} else {
				if(yych != '^') goto yy323;
			}
		} else {
			if(yych <= '|') {
				if(yych == '{') goto yy323;
			} else {
				if(yych <= '}') goto yy323;
				if(yych >= 0x7F) goto yy48;
			}
		}
	}
yy325:
	yyaccept = 4;
	YYMARKER = ++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= '@') {
		if(yych <= '+') {
			if(yych <= '#') {
				if(yych <= ' ') goto yy60;
				goto yy323;
			} else {
				if(yych <= '$') goto yy325;
				if(yych <= '*') goto yy323;
				goto yy325;
			}
		} else {
			if(yych <= ';') {
				if(yych <= '.') goto yy323;
				if(yych <= '9') goto yy325;
				goto yy323;
			} else {
				if(yych <= '<') goto yy60;
				if(yych <= '>') goto yy325;
				goto yy323;
			}
		}
	} else {
		if(yych <= '_') {
			if(yych <= '\\') {
				if(yych == '[') goto yy323;
				goto yy325;
			} else {
				if(yych == '^') goto yy325;
				goto yy323;
			}
		} else {
			if(yych <= '|') {
				if(yych == '{') goto yy323;
				goto yy325;
			} else {
				if(yych <= '}') goto yy323;
				if(yych <= '~') goto yy325;
				goto yy60;
			}
		}
	}
yy327:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0x86) goto yy144;
	if(yych <= 0xBF) goto yy50;
	goto yy48;
yy328:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xBE) goto yy50;
	if(yych <= 0xBF) goto yy331;
	goto yy48;
yy329:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0xA0) goto yy50;
	if(yych <= 0xBA) goto yy144;
	if(yych <= 0xBF) goto yy50;
	goto yy48;
yy330:
	yych = *++YYCURSOR;
	if(yych <= 0x7F) goto yy48;
	if(yych <= 0x80) goto yy50;
	if(yych <= 0x9A) goto yy144;
	if(yych <= 0xBF) goto yy50;
	goto yy48;
yy331:
	++YYCURSOR;
#line 177 "C:/Users/frane/Source/tmtorange/src/tmt/strings/UTF8Tokenizer.rr.cpp"
	{ token.mask = TokenUnicodeBOM;		return YYCURSOR; }
#line 3541 "C:/Users/frane/Source/tmtorange/src/../export/tmt/strings/UTF8Tokenizer.cpp"
}
#line 185 "C:/Users/frane/Source/tmtorange/src/tmt/strings/UTF8Tokenizer.rr.cpp"

#undef YYCTYPE
#undef YYCURSOR
#undef YYLIMIT
#undef YYMARKER
#undef YYFILL
	return NULL;
}

void UTF8Tokenizer::init(const char *s)
{
	if (retainCopy)
	{
		char *tmp;
		tmp = new char[len + 1];
		memmove(tmp, s, len);
		tmp[len] = 0;
		ptr = tmp;
	}
	else
		ptr = s;
}

UTF8Tokenizer::UTF8Tokenizer(const char *s, bool copy) : retainCopy(copy), len(strlen(s))
{
	init(s);
}

UTF8Tokenizer::UTF8Tokenizer(const string &s, bool copy) : retainCopy(copy), len(s.size())
{
	init(s.c_str());
}

UTF8Tokenizer::~UTF8Tokenizer()
{
	if (retainCopy)
		delete[] ptr;
}

UTF8Tokenizer::iterator UTF8Tokenizer::begin() const
{
	iterator it(ptr);
	if (len)
		++it;
	return it;
}
